# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7d2f7d49f77f0d43dbc0e198a7c3495066f2ec3f956d1636bfa53ae5535a1047505dc5306642e561dd97d654c68ddc8a1ca694426b4bf2bb672684a590fd0e

test:
  secret_key_base: 47da8789e30f61f41cf57529e365b6561e81ebc907d1323820e2e1d1d5b0fb186f8f9f6388cd2037d6a56d4942877afafe0d9851af0e0076a431539ceb197d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
